export const ActionTypes = {
	CREATE_TAG: 'CREATE_TAG',

	ADD_TAG_TO_CARD: 'ADD_TAG_TO_CARD',
	REMOVE_TAG_FROM_CARD: 'REMOVE_TAG_FROM_CARD',

	CREATE_CARD: 'CREATE_CARD',
	UPDATE_CARD: 'UPDATE_CARD',

	ADD_CARD_TO_LIST: 'ADD_CARD_TO_LIST',
	DELETE_CARD_FROM_LIST: 'DELETE_CARD_FROM_LIST',

	CREATE_LIST: 'CREATE_LIST',

	CREATE_BOARD: 'CREATE_BOARD',
	GET_BOARD: 'GET_BOARD',
	DELETE_LIST_FROM_BOARD: 'DELETE_LIST_FROM_BOARD',
	ADD_LIST_TO_BOARD: 'ADD_LIST_TO_BOARD',

	CREATE_USER: 'CREATE_USER',
	LOGIN_USER: 'LOGIN_USER',
	LOGOUT_USER: 'LOGOUT_USER',
	DELETE_USER: 'DELETE_USER'
}